server:
  port: 9091
spring:
  application:
    name: mmotores
  datasource:
    url: jdbc:postgresql://localhost/etapadb
    username: admin
    password: admin001
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect